### Obtener Reportes
GET http://localhost:5000/reports

### Obtener un reporte por id
GET http://localhost:5000/reports/:id

### Generar un reporte
POST http://localhost:5000/reports/create
Content-Type: application/json

{
    "title" : "Este es un reporte de artículo de ejemplo",
    "report_type" : 1,
    "author" : "Andrés Contla",
    "author_id" : "456",
    "content" : "Hubo un usuario que puso un articulo que no",
    "reported_article" : 852
}

### Generar un reporte 2
POST http://localhost:5000/reports/create
Content-Type: application/json

{
    "title" : "Este es un reporte de ejemplo",
    "report_type" : 1,
    "author" : "Luis Alfonso",
    "author_id" : "123",
    "content" : "Este es un contenido de ejemplo",
    "reported_user" : 852
}

### Actualiza un reporte por medio de un id
PUT http://localhost:5000/reports/update?reportId=6063ddfa84b7ec3e60a45858
Content-Type: application/json

{
    "title" : "Ejemplo de reporte",
    "content" : "Este es un contenido"
}

### Actualiza un reporte por medio de un id 2
PUT http://localhost:5000/reports/update?reportId=6063ddfa84b7ec3e60a45858
Content-Type: application/json


{
    "title" : "Reporte de prueba",
    "content" : "Nuevo contenido asi es"
}

### Elimina un reporte por medio de un id
DELETE http://localhost:5000/reports/delete?reportId=6064ac53dcd19f246047425a

